name: Build and test leidingbeheer

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'projects/kangoeroes-frontend-totems/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'projects/kangoeroes-frontend-totems/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run lint-core
        npm run lint-leidingbeheer
        npm run build-leidingbeheer-production
      env:
        CI: true

