name: deploy-totems-staging

on:
  push:
    branches:
     - staging
    ignore-paths:
      - 'projects/kangoeroes-frontend-leidingbeheer/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build-totems-staging
      env:
        CI: true
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: totems-staging # Replace with your app name
        publish-profile: ${{secrets.totems_staging_profile}}
        package: ./dist/totems-staging
